# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Naphat Sanguansin
subtitle: Software Developer; Tech Enthusiast
email: naphat.krit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! Welcome to my personal website! I will be writing random notes that I want to find again later and think may be useful for other people.


  If you'd like to learn more about me (work experience, projects, etc.), please see [my profile](/profile).
copyright: >
  © 2016 Naphat Sanguansin. All rights reserved.


  Made using [Jekyll](https://jekyllrb.com/) and [Bootstrap](http://getbootstrap.com/). Typeface by [DejaVu Sans Mono](https://www.fontsquirrel.com/fonts/dejavu-sans-mono) and [Source Sans Pro](https://www.google.com/fonts/specimen/Source+Sans+Pro).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://naphats.com" # the base hostname & protocol for your site
twitter_username: naphatkrit
github_username:  naphatkrit
posts_in_home: 1
top_page_ids: [blog, profile]
paginate: 5
paginate_path: "/blog/:num/"
gems: [jekyll-paginate]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      navbar_active: blog

# Build settings
markdown: kramdown
